# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuizPortal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as db

con=db.connect('QuizPortal.db')
c=con.cursor()
print(c)
con.close()

class Ui_QuizPortal(object):
    def setupUi(self, QuizPortal):
        QuizPortal.setObjectName("QuizPortal")
        QuizPortal.resize(995, 693)
        QuizPortal.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        QuizPortal.setFont(font)
        QuizPortal.setMouseTracking(True)
        QuizPortal.setAutoFillBackground(True)
        QuizPortal.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        QuizPortal.setAnimated(False)
        QuizPortal.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.MainFrame = QtWidgets.QWidget(QuizPortal)
        self.MainFrame.setObjectName("MainFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.MainFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.Admin_Tab = QtWidgets.QTabWidget(self.MainFrame)
        self.Admin_Tab.setAutoFillBackground(False)
        self.Admin_Tab.setObjectName("Admin_Tab")
        self.AdminTab = QtWidgets.QWidget()
        self.AdminTab.setObjectName("AdminTab")
        self.frame_Admin = QtWidgets.QFrame(self.AdminTab)
        self.frame_Admin.setGeometry(QtCore.QRect(10, 40, 881, 521))
        self.frame_Admin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Admin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Admin.setLineWidth(2)
        self.frame_Admin.setMidLineWidth(1)
        self.frame_Admin.setObjectName("frame_Admin")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_Admin)
        self.textBrowser.setGeometry(QtCore.QRect(30, 250, 831, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.L_Admin_info = QtWidgets.QLabel(self.frame_Admin)
        self.L_Admin_info.setGeometry(QtCore.QRect(160, 40, 421, 51))
        self.L_Admin_info.setObjectName("L_Admin_info")
        self.input_file_path = QtWidgets.QLineEdit(self.frame_Admin)
        self.input_file_path.setGeometry(QtCore.QRect(150, 110, 451, 31))
        self.input_file_path.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.input_file_path.setObjectName("input_file_path")
        self.btn_UploadFile = QtWidgets.QPushButton(self.frame_Admin)
        self.btn_UploadFile.setGeometry(QtCore.QRect(280, 180, 171, 41))
        self.btn_UploadFile.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_UploadFile.setAutoFillBackground(True)
        self.btn_UploadFile.setObjectName("btn_UploadFile")
        self.input_file_path.raise_()
        self.L_Admin_info.raise_()
        self.btn_UploadFile.raise_()
        self.frame_Admin.raise_()
        self.Admin_Tab.addTab(self.AdminTab, "")
        self.Student_registration_tab = QtWidgets.QWidget()
        self.Student_registration_tab.setObjectName("Student_registration_tab")
        self.frame_Student_Reg_Input = QtWidgets.QFrame(self.Student_registration_tab)
        self.frame_Student_Reg_Input.setGeometry(QtCore.QRect(0, 10, 641, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Student_Reg_Input.sizePolicy().hasHeightForWidth())
        self.frame_Student_Reg_Input.setSizePolicy(sizePolicy)
        self.frame_Student_Reg_Input.setBaseSize(QtCore.QSize(100, 100))
        self.frame_Student_Reg_Input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Student_Reg_Input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Student_Reg_Input.setObjectName("frame_Student_Reg_Input")
        self.L_Student_Reg_info = QtWidgets.QLabel(self.frame_Student_Reg_Input)
        self.L_Student_Reg_info.setGeometry(QtCore.QRect(120, 10, 431, 51))
        self.L_Student_Reg_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_Student_Reg_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.L_Student_Reg_info.setIndent(0)
        self.L_Student_Reg_info.setObjectName("L_Student_Reg_info")
        self.L_Student_name = QtWidgets.QLabel(self.frame_Student_Reg_Input)
        self.L_Student_name.setGeometry(QtCore.QRect(230, 80, 141, 31))
        self.L_Student_name.setIndent(0)
        self.L_Student_name.setObjectName("L_Student_name")
        self.input_Student_Name = QtWidgets.QLineEdit(self.frame_Student_Reg_Input)
        self.input_Student_Name.setGeometry(QtCore.QRect(150, 120, 331, 41))
        self.input_Student_Name.setClearButtonEnabled(True)
        self.input_Student_Name.setObjectName("input_Student_Name")
        self.L_Course_id = QtWidgets.QLabel(self.frame_Student_Reg_Input)
        self.L_Course_id.setGeometry(QtCore.QRect(210, 190, 199, 20))
        self.L_Course_id.setIndent(0)
        self.L_Course_id.setObjectName("L_Course_id")
        self.input_course_id = QtWidgets.QLineEdit(self.frame_Student_Reg_Input)
        self.input_course_id.setGeometry(QtCore.QRect(150, 240, 341, 41))
        self.input_course_id.setClearButtonEnabled(True)
        self.input_course_id.setObjectName("input_course_id")
        self.L_student_id = QtWidgets.QLabel(self.frame_Student_Reg_Input)
        self.L_student_id.setGeometry(QtCore.QRect(240, 320, 163, 20))
        self.L_student_id.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_student_id.setTextFormat(QtCore.Qt.PlainText)
        self.L_student_id.setIndent(0)
        self.L_student_id.setObjectName("L_student_id")
        self.inuput_student_id = QtWidgets.QLineEdit(self.frame_Student_Reg_Input)
        self.inuput_student_id.setGeometry(QtCore.QRect(150, 370, 341, 51))
        self.inuput_student_id.setText("")
        self.inuput_student_id.setClearButtonEnabled(True)
        self.inuput_student_id.setObjectName("inuput_student_id")
        self.btn_Student_detail = QtWidgets.QPushButton(self.frame_Student_Reg_Input)
        self.btn_Student_detail.setGeometry(QtCore.QRect(90, 480, 151, 41))
        self.btn_Student_detail.setObjectName("btn_Student_detail")
        self.btn_clear_student_details = QtWidgets.QPushButton(self.frame_Student_Reg_Input)
        self.btn_clear_student_details.setGeometry(QtCore.QRect(360, 480, 161, 41))
        self.btn_clear_student_details.setObjectName("btn_clear_student_details")
        self.frame_Studetn_Reg_Status = QtWidgets.QFrame(self.Student_registration_tab)
        self.frame_Studetn_Reg_Status.setGeometry(QtCore.QRect(680, 10, 271, 561))
        self.frame_Studetn_Reg_Status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Studetn_Reg_Status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Studetn_Reg_Status.setObjectName("frame_Studetn_Reg_Status")
        self.input_sql_status = QtWidgets.QLineEdit(self.frame_Studetn_Reg_Status)
        self.input_sql_status.setGeometry(QtCore.QRect(30, 90, 221, 411))
        self.input_sql_status.setObjectName("input_sql_status")
        self.L_Status = QtWidgets.QLabel(self.frame_Studetn_Reg_Status)
        self.L_Status.setGeometry(QtCore.QRect(70, 40, 81, 31))
        self.L_Status.setObjectName("L_Status")
        self.Admin_Tab.addTab(self.Student_registration_tab, "")
        self.Quiz_Tab = QtWidgets.QWidget()
        self.Quiz_Tab.setObjectName("Quiz_Tab")
        self.frame_Quiz = QtWidgets.QFrame(self.Quiz_Tab)
        self.frame_Quiz.setGeometry(QtCore.QRect(20, 10, 900, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Quiz.sizePolicy().hasHeightForWidth())
        self.frame_Quiz.setSizePolicy(sizePolicy)
        self.frame_Quiz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Quiz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Quiz.setObjectName("frame_Quiz")
        self.pushButton = QtWidgets.QPushButton(self.frame_Quiz)
        self.pushButton.setGeometry(QtCore.QRect(300, 220, 141, 111))
        self.pushButton.setObjectName("pushButton")
        self.Admin_Tab.addTab(self.Quiz_Tab, "")
        self.gridLayout.addWidget(self.Admin_Tab, 1, 0, 1, 1)
        QuizPortal.setCentralWidget(self.MainFrame)
        self.menubar = QtWidgets.QMenuBar(QuizPortal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        QuizPortal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QuizPortal)
        self.statusbar.setObjectName("statusbar")
        QuizPortal.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(QuizPortal)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(QuizPortal)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPython_Version_Used = QtWidgets.QAction(QuizPortal)
        self.actionPython_Version_Used.setObjectName("actionPython_Version_Used")
        self.menuMain.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionPython_Version_Used)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(QuizPortal)
        self.Admin_Tab.setCurrentIndex(0)
        self.btn_clear_student_details.clicked.connect(self.input_Student_Name.clear)
        self.btn_clear_student_details.clicked.connect(self.input_course_id.clear)
        self.btn_clear_student_details.clicked.connect(self.inuput_student_id.clear)
        self.btn_Student_detail.clicked.connect(self.input_Student_Name.selectAll)
        self.btn_Student_detail.clicked.connect(self.input_course_id.selectAll)
        self.btn_Student_detail.clicked.connect(self.inuput_student_id.selectAll)
        self.btn_Student_detail.clicked.connect(self.input_sql_status.show)
        QtCore.QMetaObject.connectSlotsByName(QuizPortal)
        QuizPortal.setTabOrder(self.btn_Student_detail, self.input_file_path)
        QuizPortal.setTabOrder(self.input_file_path, self.inuput_student_id)
        QuizPortal.setTabOrder(self.inuput_student_id, self.btn_clear_student_details)
        QuizPortal.setTabOrder(self.btn_clear_student_details, self.input_course_id)
        QuizPortal.setTabOrder(self.input_course_id, self.input_Student_Name)
        QuizPortal.setTabOrder(self.input_Student_Name, self.pushButton)
        QuizPortal.setTabOrder(self.pushButton, self.textBrowser)
        QuizPortal.setTabOrder(self.textBrowser, self.input_sql_status)
        QuizPortal.setTabOrder(self.input_sql_status, self.Admin_Tab)
        QuizPortal.setTabOrder(self.Admin_Tab, self.btn_UploadFile)

    def retranslateUi(self, QuizPortal):
        _translate = QtCore.QCoreApplication.translate
        QuizPortal.setWindowTitle(_translate("QuizPortal", "Quiz Portal"))
        self.textBrowser.setHtml(_translate("QuizPortal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cambria\'; font-size:12pt; font-weight:600; text-decoration: underline;\">Note</span><span style=\" font-family:\'Cambria\'; font-size:12pt; font-weight:600;\"> :</span><span style=\" font-family:\'Cambria\'; font-size:10pt; font-weight:600;\"> </span><span style=\" font-family:\'Cambria\'; font-size:10pt;\">Only CSV file in the following format is accepted. </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cambria\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cambria\'; font-size:10pt;\">The header should have following cells</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cambria\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cambria\'; font-size:10pt;\">Question_text,Option_1,Option_2,Option_3,Option_4,Answer_text</span></p></body></html>"))
        self.L_Admin_info.setText(_translate("QuizPortal", "Browse or enter the file path to upload your CSV file"))
        self.input_file_path.setAccessibleName(_translate("QuizPortal", "file_input"))
        self.btn_UploadFile.setText(_translate("QuizPortal", "Upload"))
        self.Admin_Tab.setTabText(self.Admin_Tab.indexOf(self.AdminTab), _translate("QuizPortal", "Admin"))
        self.L_Student_Reg_info.setText(_translate("QuizPortal", "Students can register for new courses here"))
        self.L_Student_name.setText(_translate("QuizPortal", "Student Name"))
        self.input_Student_Name.setPlaceholderText(_translate("QuizPortal", "Enter Name"))
        self.L_Course_id.setText(_translate("QuizPortal", "Course ID (like DATA650)"))
        self.input_course_id.setPlaceholderText(_translate("QuizPortal", "Course "))
        self.L_student_id.setText(_translate("QuizPortal", "Student ID (axy@31)"))
        self.inuput_student_id.setPlaceholderText(_translate("QuizPortal", "Enter id"))
        self.btn_Student_detail.setText(_translate("QuizPortal", "Submit Details"))
        self.btn_clear_student_details.setText(_translate("QuizPortal", "Clear Details"))
        self.L_Status.setText(_translate("QuizPortal", "Status"))
        self.Admin_Tab.setTabText(self.Admin_Tab.indexOf(self.Student_registration_tab), _translate("QuizPortal", "Student Registration"))
        self.pushButton.setText(_translate("QuizPortal", "PushButton"))
        self.Admin_Tab.setTabText(self.Admin_Tab.indexOf(self.Quiz_Tab), _translate("QuizPortal", "Quiz"))
        self.menuMain.setTitle(_translate("QuizPortal", "Main"))
        self.menuHelp.setTitle(_translate("QuizPortal", "Help"))
        self.actionExit.setText(_translate("QuizPortal", "Exit"))
        self.actionAbout.setText(_translate("QuizPortal", "About"))
        self.actionPython_Version_Used.setText(_translate("QuizPortal", "Python Version Used"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuizPortal = QtWidgets.QMainWindow()
    ui = Ui_QuizPortal()
    ui.setupUi(QuizPortal)
    QuizPortal.show()
    sys.exit(app.exec_())

